project_name: hauler
before:
  hooks:
    - go mod tidy
    - go mod download

env:
  - vpkg=github.com/rancherfederal/hauler/pkg/version

builds:
  - main: cmd/hauler/main.go
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X {{ .Env.vpkg }}.GitVersion={{ .Version }} -X {{ .Env.vpkg }}.commit={{ .ShortCommit }} -X {{ .Env.vpkg }}.buildDate={{ .Date }}
    env:
      - CGO_ENABLED=0

universal_binaries:
  - replace: true

changelog:
  skip: false
  use: git

brews:
  - name: hauler
    tap:
      owner: rancherfederal
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    folder: Formula
    description: "Hauler CLI"
