{{- if and .Values.haulerRegistry.enabled .Values.haulerRegistry.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hauler-registry
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hauler.labels" . | nindent 4 }}
spec:
  rules:
  {{- range .Values.haulerRegistry.ingress.hosts }}
  - host: {{ . }}
    http:
      paths:
      - backend:
          service:
            name: hauler-registry
            port:
              number: {{ $.Values.haulerRegistry.service.ports.targetPort }}
        path: /
        pathType: Prefix
  {{- end }}
  {{- if .Values.haulerRegistry.ingress.tls.enabled }}
  tls:
  - hosts:
    {{- range .Values.haulerRegistry.ingress.hosts }}
    - {{ . }}
    {{- end }}
    secretName: {{ .Values.haulerRegistry.ingress.tls.secretName }}
  {{- end }}
{{- end }}
