# Helm Chart Values for Hauler
# Docs: http://hauler.dev

hauler:
  image:
    repository: ghcr.io/rancherfederal/hauler
    tag: v1.0.2-rc.4
  imagePullPolicy: Always

  initContainers:
    image:
      repository: rancher/kubectl
      tag: v1.27.0
    imagePullPolicy: Always
    timeout: 1h

  data:
    pvc:
      accessModes: ReadWriteMany
      storageClass: longhorn
      storageRequest: 48Gi

  port: 80

  ingress:
    enabled: true
    hosts:
      - hauler.ranchers.io
    tls:
      enabled: true
      secretName: tls-certs

  service:
    enabled: true
    type: ClusterIP
    ports:
      name: hauler
      protocol: TCP
      port: 80
      targetPort: 80

# Helm Chart Values for the Hauler Jobs
# Docs: https://rancherfederal.github.io/hauler-docs/docs/introduction/quickstart

haulerJobs:
  image:
    repository: rancher/shell
    tag: v0.1.22
  imagePullPolicy: Always

  hauls:
    enabled: true
    artifacts:
      - path: https://rancher-airgap.s3.amazonaws.com/longhorn.tar.zst
        name: longhorn.tar.zst
      - path: https://rancher-airgap.s3.amazonaws.com/neuvector.tar.zst
        name: neuvector.tar.zst

  manifests:
    enabled: true
    artifacts:
      - path: https://rancher-airgap.s3.amazonaws.com/rancher-airgap-cosign.yaml
        name: rancher-airgap-cosign.yaml
      - path: https://rancher-airgap.s3.amazonaws.com/rancher-airgap-helm.yaml
        name: rancher-airgap-helm.yaml

# Helm Chart Values for the Hauler Fileserver
# Docs: https://rancherfederal.github.io/hauler-docs/docs/guides-references/command-line/hauler-store#hauler-store-serve-fileserver

haulerFileserver:
  enabled: true

  port: 8080

  ingress:
    enabled: true
    hosts:
      - fileserver.ranchers.io
    tls:
      enabled: true
      secretName: tls-certs

  service:
    enabled: true
    type: ClusterIP
    ports:
      name: hauler-fileserver
      protocol: TCP
      port: 8080
      targetPort: 8080

# Helm Chart Values for the Hauler Registry
# Docs: https://rancherfederal.github.io/hauler-docs/docs/guides-references/command-line/hauler-store#hauler-store-serve-registry

haulerRegistry:
  enabled: true

  port: 5000

  ingress:
    enabled: true
    hosts:
      - registry.ranchers.io
    tls:
      enabled: true
      secretName: tls-certs

  service:
    enabled: true
    type: ClusterIP
    ports:
      name: hauler-registry
      protocol: TCP
      port: 5000
      targetPort: 5000
