---
apiVersion: v1
kind: Namespace
metadata:
  name: gitea
  labels:
    app.kubernetes.io/name: hauler
    app.kubernetes.io/managed-by: hauler

---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: stuart
  namespace: hauler
  labels:
    app.kubernetes.io/name: hauler
    app.kubernetes.io/managed-by: hauler
spec:
  chart: https://%{KUBERNETES_API}%/static/charts/gitea-3.0.0.tgz
  targetNamespace: gitea
  valuesContent: |-
    persistence:
      enabled: true
    image:
      pullPolicy: Never
      rootless: true
      repository: gitea/gitea
      tag: 1.14.1
    service:
      http:
        type: ClusterIP
    gitea:
      admin:
        username: "hauler"
        password: "hauler123"
      cache:
        builtIn:
          enabled: false
      config:
        APP_NAME: "Hauler Gitea"
        database:
          DB_TYPE: sqlite3
        service:
          DISABLE_REGISTRATION: true
        repository:
          ENABLE_PUSH_CREATE_USER: true
          FORCE_PRIVATE: true

      database:
        builtIn:
          postgresql:
            enabled: false
