---
apiVersion: v1
kind: Namespace
metadata:
  name: registry
  labels:
    app.kubernetes.io/name: hauler
    app.kubernetes.io/managed-by: hauler

---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: kevin
  namespace: hauler
  labels:
    app.kubernetes.io/name: hauler
    app.kubernetes.io/managed-by: hauler
spec:
  chart: https://%{KUBERNETES_API}%/static/charts/docker-registry-1.10.1.tgz
  targetNamespace: registry
  valuesContent: |-
    persistence:
      enabled: true

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: registry
  namespace: registry
  labels:
    app.kubernetes.io/name: hauler
    app.kubernetes.io/managed-by: hauler
spec:
  entryPoints:
    - registry
  routes:
    - match: HostSNI(`*`)
      kind: Rule
      services:
        - name: kevin-docker-registry
          port: 5000
