apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    deployment:
      kind: DaemonSet
    additionalArguments:
      - --entrypoints.registry.address=:5000
      - --entrypoints.git.address=:9696
    ports:
      registry:
        port: 5000
        expose: true
        exposedPort: 5000
        protocol: TCP
      git:
        port: 3000
        expose: true
        exposedPort: 3000
        protocol: TCP
