apiVersion: v1
kind: Namespace
metadata:
  name: registry

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: docker-registry
  namespace: registry
data:
  registry-config.yml: |
    version: 0.1
    log:
      fields:
        service: registry
    storage:
      cache:
        blobdescriptor: inmemory
      filesystem:
        rootdirectory: /var/lib/registry
    http:
      addr: :5000
      headers:
        X-Content-Type-Options: [nosniff]
    # auth:
    #   htpasswd:
    #     realm: basic-realm
    #     path: /auth/htpasswd
    health:
      storagedriver:
        enabled: true
        interval: 10s
        threshold: 3

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: deployment-registry-registry
  name: registry
  namespace: registry
spec:
  replicas: 1
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-registry-registry
  template:
    metadata:
      labels:
        workload.user.cattle.io/workloadselector: deployment-registry-registry
    spec:
      containers:
      - image: registry:2
        imagePullPolicy: Always
        name: registry
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        - mountPath: /var/lib/registry
          name: registryvol
        - name: config
          mountPath: /etc/docker/registry
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: registryvol
        persistentVolumeClaim:
          claimName: registryvol
      - name: config
        configMap:
          name: docker-registry
          items:
            - key: registry-config.yml
              path: config.yml

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    cattle.io/creator: norman
  name: registryvol
  namespace: registry
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi


---

apiVersion: v1
kind: Service
metadata:
  labels:
    cattle.io/creator: norman
  name: registrysvc
  namespace: registry
spec:
  ports:
  - name: httpregistry
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    workload.user.cattle.io/workloadselector: deployment-registry-registry
  sessionAffinity: None
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  labels:
    cattle.io/creator: norman
    foo: bar
  name: registrynodeport
  namespace: registry
spec:
  ports:
  - name: http
    nodePort: 30500
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    workload.user.cattle.io/workloadselector: deployment-registry-registry
  sessionAffinity: None
  type: NodePort

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
    cattle.io/creator: norman
  name: registryingress
  namespace: registry
spec:
  rules:
  - host: registry
    http:
      paths:
      - backend:
          serviceName: registrysvc
          servicePort: 5000
        pathType: ImplementationSpecific
