name: Unit Test Workflow

on:
  push:
    paths-ignore:
      - '**.md'
      - '.github/**'
      - '!.github/workflows/unittest.yaml'
  pull_request:
    paths-ignore:
      - '**.md'
      - '.github/**'
      - '!.github/workflows/unitcoverage.yaml'
  workflow_dispatch: {}

jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21.x
      - name: Run Unit Tests
        run: |
          mkdir -p cmd/hauler/binaries
          touch cmd/hauler/binaries/dummy.txt
          go test -race -covermode=atomic -coverprofile=coverage.out ./pkg/... ./internal/... ./cmd/...
      - name: On Failure, Launch Debug Session
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3
        timeout-minutes: 5
      - name: Upload Results To Codecov
        uses: codecov/codecov-action@v1
        with:
          files: ./coverage.out
          verbose: true # optional (default = false)
